spring.application.name=api-gateway
server.port=8080
spring.main.web-application-type=reactive
eureka.client.serviceUrl.defaultZone=http://${discovery.host}:${discovery.port}/eureka/
app.clients.auth-service.name=auth-service
app.clients.file-service.name=file-service
app.clients.main-service.name=main-service
app.clients.notification-service.name=notification-service
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedHeaders=*