spring.application.name=api-gateway
server.port=8080
spring.main.web-application-type=reactive
eureka.client.serviceUrl.defaultZone=http://${discovery.host}:${discovery.port}/eureka/
#Redis properties
spring.data.redis.host=${redis.host}
spring.data.redis.port=${redis.port}
spring.data.redis.user=${redis.username}
spring.data.redis.password=${redis.password}
# Observability
management.health.readinessState.enabled=true
management.health.livenessState.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=true
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=api-gateway
#Cors properties
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedorigins=${cors.allowed.origins:*}
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedmethods=${cors.allowed.methods:*}
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedheaders=${cors.allowed.headers:*}
#App properties
app.token.signing.key=${auth.token.signing.key}
#Clients properties
app.clients.auth-service.name=auth-service
app.clients.file-service.name=file-service
app.clients.main-service.name=main-service
app.clients.notification-service.name=notification-service