spring.application.name=api-gateway
server.port=8080
spring.main.web-application-type=reactive
eureka.client.serviceUrl.defaultZone=http://${discovery.host}:${discovery.port}/eureka/
app.auth.url=http://auth-service
app.main.url=http://main-service
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedHeaders=*